// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('noiseAlert.app', []);

  app.config([
    '$interpolateProvider', function($interpolateProvider) {
      $interpolateProvider.startSymbol('{[{');
      return $interpolateProvider.endSymbol('}]}');
    }
  ]);

  app.controller('noiseController', [
    '$scope', '$window', function($scope, $window) {
      $scope.phoneNumber = '408';
      $scope.threshold = 0.2;
      $window.noiseAlert = {
        threshold: $scope.threshold
      };
      return $scope.$watch('threshold', function(newValue) {
        return $window.noiseAlert.threshold = newValue;
      });
    }
  ]);

}).call(this);
