// Generated by CoffeeScript 1.7.1
(function() {
  var app, errorCallback;

  app = angular.module('noiseAlert.app', []);

  app.config([
    '$interpolateProvider', function($interpolateProvider) {
      $interpolateProvider.startSymbol('{[{');
      return $interpolateProvider.endSymbol('}]}');
    }
  ]);

  app.controller('noiseController', [
    '$scope', '$window', 'SoundMeter', function($scope, $window, SoundMeter) {
      var audioContext, constraints, e, successCallback;
      try {
        $window.AudioContext = $window.AudioContext || $window.webkitAudioContext;
        audioContext = new AudioContext();
      } catch (_error) {
        e = _error;
        alert('Web Audio API not supported.');
      }
      constraints = {
        audio: true,
        video: false
      };
      navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
      return successCallback = function(stream) {
        var soundMeter;
        soundMeter = new SoundMeter(audioContext);
        soundMeter.connectToSource(stream);
        return setInterval(function() {
          $scope.instantVolume = soundMeter.instant.toFixed(2);
          $scope.noiseProgress = soundMeter.noiseProgress.toFixed(5);
          return $scope.topNoises = soundMeter.topNoises;
        }, 200);
      };
    }, errorCallback = function(error) {
      return console.log('navigator.getUserMedia error: ', error);
    }, navigator.getUserMedia(constraints, successCallback, errorCallback), $scope.phoneNumber = '408', $scope.threshold = 0.2
  ]);

}).call(this);
